import {
    LayoutDashboard,
    ShoppingCart,
    Package,
    Truck,
    Gift,
    Warehouse,
    Wallet,
    ArrowRightLeft,
    Users,
    ImageIcon,
    Star,
    UserCheck,
    FileBarChart,
    Bell,
    MessageSquare,
    Store,
} from "lucide-react";
import { NavItem } from "@/types";

export const sidebarNavItems: NavItem[] = [
    { titleKey: "sidebar.dashboard", href: "/dashboard", icon: LayoutDashboard },
    {
        titleKey: "sidebar.order_management",
        href: "/orders",
        icon: ShoppingCart,
        children: [
            { titleKey: "sidebar.new_order", href: "/orders/new" },
            { titleKey: "sidebar.order_list", href: "/orders/list" },
            { titleKey: "sidebar.order_assigned", href: "/orders/assigned" },
            { titleKey: "sidebar.cancel_order", href: "/orders/cancel" },
            { titleKey: "sidebar.delivery_completed", href: "/orders/completed" },
        ],
    },
    {
        titleKey: "sidebar.product_management",
        href: "/products",
        icon: Package,
        children: [
            { titleKey: "sidebar.product_list", href: "/products/list" },
            { titleKey: "sidebar.category_list", href: "/products/categories" },
            { titleKey: "sidebar.sub_category", href: "/products/sub-categories" },
            { titleKey: "sidebar.product_type", href: "/products/types" },
        ],
    },
    {
        titleKey: "sidebar.delivery_management",
        href: "/delivery",
        icon: Truck,
        children: [{ titleKey: "sidebar.delivery_men", href: "/delivery/men" }],
    },
    {
        titleKey: "sidebar.reward_referral",
        href: "/rewards",
        icon: Gift,
        children: [],
    },
    {
        titleKey: "sidebar.inventory",
        href: "/inventory",
        icon: Warehouse,
        children: [],
    },
    {
        titleKey: "sidebar.finance_expenses",
        href: "/finance",
        icon: Wallet,
        children: [],
    },
    {
        titleKey: "sidebar.transaction",
        href: "/transactions",
        icon: ArrowRightLeft,
        children: [],
    },
    { titleKey: "sidebar.customer", href: "/customers", icon: Users },
    { titleKey: "sidebar.banner", href: "/banners", icon: ImageIcon },
    {
        titleKey: "sidebar.review_management",
        href: "/reviews",
        icon: Star,
        children: [],
    },
    { titleKey: "sidebar.followers", href: "/followers", icon: UserCheck },
    {
        titleKey: "sidebar.report",
        href: "/reports",
        icon: FileBarChart,
        children: [],
    },
    { titleKey: "sidebar.notification", href: "/notifications", icon: Bell },
    { titleKey: "sidebar.messages", href: "/messages", icon: MessageSquare },
    { titleKey: "sidebar.vendor_management", href: "/vendors", icon: Store },
];
